### ISSUE TITLE
Can it remember the details and not ask for password every time

### ISSUE THREAD

**Issue by nikitavoloboev** [bradyjoslin/wifi-password#1]
It's very annoying having to type username and password every time I want to share the password.

**Comment by bradyjoslin** [comment]
Not currently aware of a way to pass credentials to the macOS `security` utility used by the app to obtain the wi-fi passwords stored in the system keychain.

**Comment by bradyjoslin** [comment]
New flag --always-allow added to prevent future password prompts.

` -a, --always-allow    Disables future confirmation prompts to access this password. Sudo required`

**Comment by nikitavoloboev** [comment]
Very cool, thx
